export { HomeView } from "./home";
export { BasicsView } from "./basics";
export { WhitepaperView } from "./whitepaper";
export { TeamView } from "./team";
export { AcademyView } from "./academy";
export { HackView } from "./hackbros"
export { UnderConstructionView } from "./underconstruction"
export { NftView } from "./nftpage"
export { RarityView } from "./rarity"
